In [4]:
test_input = """00100
11110
10110
10111
10101
01111
00111
11100
10000
11001
00010
01010""".splitlines();

In [20]:
import numpy as np;
def binary_calculate(input):
    #so some thoughts needed here. i dont konw how to solve that in bits so will split to arrays.
    ln=0
    bisum=np.array([0] * len(input[0]))
    for bin in input:
        ln +=1
        bits = np.array(list(bin), dtype=int)
        bisum = bits+bisum
        print (bits, bisum)
    
    a=0;b=0;
    for s in bisum:
        if (s>= ln/2):
            #probably there is a included function to work with binaries
            a=a*2+1
            b=b*2+0
        else:
            a=a*2+0
            b=b*2+1
    print (a, b)
    print ("answer is " +str(a*b))
    return a, b
        
        

In [78]:
import copy
def binary_search_excluding (input):
    
    list1 = copy.deepcopy(input)
    list2 = copy.deepcopy(input)
    for n in range (0,len(input[0])):
            counter = 0
            for a in list1:
                if (a[n]=="1"):
                    counter +=1;
                    
            result="1" if counter>=len(list1)/2 else result="0"
            
            print (n, result, list1)
            list1 =[a for a in list1 if a[n]==result or len(list1)==1]
            print (n, result, list1)
            
            counter = 0
            for a in list2:
                if (a[n]=="1"):
                    counter +=1;
            result="1" if counter<len(list2)/2 else result="0"
            
            print (n, result, list2)
            list2 =[a for a in list2 if a[n]==result or len(list2)==1]
            print (n, result, list2)
            
            if (len(list1)==1 and len(list2)==1): break
    o1 = int(list1[0],2)
    o2 = int(list2[0],2)         
    
    print (list1, list2)
    print (o1,o2)
    print ("answer is" + str(o1*o2))
    


SyntaxError: cannot assign to conditional expression (<ipython-input-78-2e06ebf55ddf>, line 12)

In [79]:
binary_search_excluding(test_input)

0 1 ['00100', '11110', '10110', '10111', '10101', '01111', '00111', '11100', '10000', '11001', '00010', '01010']
0 1 ['11110', '10110', '10111', '10101', '11100', '10000', '11001']
0 0 ['00100', '11110', '10110', '10111', '10101', '01111', '00111', '11100', '10000', '11001', '00010', '01010']
0 0 ['00100', '01111', '00111', '00010', '01010']
1 0 ['11110', '10110', '10111', '10101', '11100', '10000', '11001']
1 0 ['10110', '10111', '10101', '10000']
1 1 ['00100', '01111', '00111', '00010', '01010']
1 1 ['01111', '01010']
2 1 ['10110', '10111', '10101', '10000']
2 1 ['10110', '10111', '10101']
2 0 ['01111', '01010']
2 0 ['01010']
3 1 ['10110', '10111', '10101']
3 1 ['10110', '10111']
3 0 ['01010']
3 0 ['01010']
4 1 ['10110', '10111']
4 1 ['10111']
4 1 ['01010']
4 1 ['01010']
['10111'] ['01010']
23 10
answer is230


In [77]:
%run ./util.ipynb
binary_search_excluding(read_file('day3'))

0 0 ['110001010111', '011011110010', '110011110011', '101000010111', '011101100100', '111001011100', '011100000101', '011110110011', '001001111111', '111000010000', '001000101100', '011100111010', '011100111000', '011100010001', '100001100000', '111010111110', '100011000101', '010111000101', '100110110011', '101010110011', '110101110010', '110111100010', '000001100100', '010010011010', '001001001100', '101000000111', '100100110011', '111111100011', '110010001010', '100010110011', '111101101001', '101001001101', '110111011101', '100100101101', '111111000011', '001110010110', '010110110010', '010011100000', '110011100011', '111101001011', '100001101000', '100101100011', '010101100110', '101000001001', '010001011100', '111001010010', '000110000110', '110110111111', '111111010000', '110111110011', '110110010010', '000001001111', '010001000111', '101101100110', '110011100100', '101000010100', '010100010000', '100011001001', '011000111101', '000101011101', '000110111110', '011000101100', '11

In [24]:
binary_calculate(test_input)

[0 0 1 0 0] [0 0 1 0 0]
[1 1 1 1 0] [1 1 2 1 0]
[1 0 1 1 0] [2 1 3 2 0]
[1 0 1 1 1] [3 1 4 3 1]
[1 0 1 0 1] [4 1 5 3 2]
[0 1 1 1 1] [4 2 6 4 3]
[0 0 1 1 1] [4 2 7 5 4]
[1 1 1 0 0] [5 3 8 5 4]
[1 0 0 0 0] [6 3 8 5 4]
[1 1 0 0 1] [7 4 8 5 5]
[0 0 0 1 0] [7 4 8 6 5]
[0 1 0 1 0] [7 5 8 7 5]
22 9
answer is 198


198

In [26]:
%run ./util.ipynb
binary_calculate(read_file('day3'))

[1 1 0 0 0 1 0 1 0 1 1 1] [1 1 0 0 0 1 0 1 0 1 1 1]
[0 1 1 0 1 1 1 1 0 0 1 0] [1 2 1 0 1 2 1 2 0 1 2 1]
[1 1 0 0 1 1 1 1 0 0 1 1] [2 3 1 0 2 3 2 3 0 1 3 2]
[1 0 1 0 0 0 0 1 0 1 1 1] [3 3 2 0 2 3 2 4 0 2 4 3]
[0 1 1 1 0 1 1 0 0 1 0 0] [3 4 3 1 2 4 3 4 0 3 4 3]
[1 1 1 0 0 1 0 1 1 1 0 0] [4 5 4 1 2 5 3 5 1 4 4 3]
[0 1 1 1 0 0 0 0 0 1 0 1] [4 6 5 2 2 5 3 5 1 5 4 4]
[0 1 1 1 1 0 1 1 0 0 1 1] [4 7 6 3 3 5 4 6 1 5 5 5]
[0 0 1 0 0 1 1 1 1 1 1 1] [4 7 7 3 3 6 5 7 2 6 6 6]
[1 1 1 0 0 0 0 1 0 0 0 0] [5 8 8 3 3 6 5 8 2 6 6 6]
[0 0 1 0 0 0 1 0 1 1 0 0] [5 8 9 3 3 6 6 8 3 7 6 6]
[0 1 1 1 0 0 1 1 1 0 1 0] [ 5  9 10  4  3  6  7  9  4  7  7  6]
[0 1 1 1 0 0 1 1 1 0 0 0] [ 5 10 11  5  3  6  8 10  5  7  7  6]
[0 1 1 1 0 0 0 1 0 0 0 1] [ 5 11 12  6  3  6  8 11  5  7  7  7]
[1 0 0 0 0 1 1 0 0 0 0 0] [ 6 11 12  6  3  7  9 11  5  7  7  7]
[1 1 1 0 1 0 1 1 1 1 1 0] [ 7 12 13  6  4  7 10 12  6  8  8  7]
[1 0 0 0 1 1 0 0 0 1 0 1] [ 8 12 13  6  5  8 10 12  6  9  8  8]
[0 1 0 1 1 1 0 0 0 1 0 1] [ 8 13 13  7  6  9

2583164