In [1]:
test_input = """7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7""".splitlines();

In [49]:
def read_input (input):
    sequence = list(map(int, input[0].split(",")))
    start=2
    bingos = []
    while start+5<=len(input):
        bingos.append([list(map(int, (i.split()))) for i in input[start:start+5]])
        start+=6
    return sequence, bingos

In [81]:
import numpy as np

def check_bingo (b):
    bingo=np.array(b);
    if (min(np.concatenate((np.sum(bingo, axis=0),np.sum(bingo, axis=1)), axis=0))==-5):
        return 1
    return 0

In [84]:
import numpy as np
def play_bingo (input):
    seq, b = read_input(input)
    bingos = np.array(b)
    for a in seq:
        print(a, bingos)
        bingos = np.where(bingos==a, -1, bingos)
        print(a,bingos)
        for bingo in bingos:
            if check_bingo (bingo):
                print("BINGO")
                print (bingo)
                sum = np.sum(np.where(bingo==-1,0,bingo))
                print (sum)
                return sum*a

        

In [103]:
import numpy as np
def play_bingo_last (input):
    seq, b = read_input(input)
    bingos = np.array(b)
    for a in seq:
        print(a, bingos)
        bingos = np.where(bingos==a, -1, bingos)
        print(a,bingos)
        if len(bingos)>1:
            bingos =np.array([b for b in bingos if not check_bingo(b)])
        elif check_bingo (bingos[0]):
                bingo=bingos[0]
                print("LAST BINGO")
                print (bingo)
                sum = np.sum(np.where(bingo==-1,0,bingo))
                print (sum)
                return sum*a


In [85]:
play_bingo (test_input)

7 [[[22 13 17 11  0]
  [ 8  2 23  4 24]
  [21  9 14 16  7]
  [ 6 10  3 18  5]
  [ 1 12 20 15 19]]

 [[ 3 15  0  2 22]
  [ 9 18 13 17  5]
  [19  8  7 25 23]
  [20 11 10 24  4]
  [14 21 16 12  6]]

 [[14 21 17 24  4]
  [10 16 15  9 19]
  [18  8 23 26 20]
  [22 11 13  6  5]
  [ 2  0 12  3  7]]]
7 [[[22 13 17 11  0]
  [ 8  2 23  4 24]
  [21  9 14 16 -1]
  [ 6 10  3 18  5]
  [ 1 12 20 15 19]]

 [[ 3 15  0  2 22]
  [ 9 18 13 17  5]
  [19  8 -1 25 23]
  [20 11 10 24  4]
  [14 21 16 12  6]]

 [[14 21 17 24  4]
  [10 16 15  9 19]
  [18  8 23 26 20]
  [22 11 13  6  5]
  [ 2  0 12  3 -1]]]
4 [[[22 13 17 11  0]
  [ 8  2 23  4 24]
  [21  9 14 16 -1]
  [ 6 10  3 18  5]
  [ 1 12 20 15 19]]

 [[ 3 15  0  2 22]
  [ 9 18 13 17  5]
  [19  8 -1 25 23]
  [20 11 10 24  4]
  [14 21 16 12  6]]

 [[14 21 17 24  4]
  [10 16 15  9 19]
  [18  8 23 26 20]
  [22 11 13  6  5]
  [ 2  0 12  3 -1]]]
4 [[[22 13 17 11  0]
  [ 8  2 23 -1 24]
  [21  9 14 16 -1]
  [ 6 10  3 18  5]
  [ 1 12 20 15 19]]

 [[ 3 15  0  2 22]
  [

4512

In [104]:
play_bingo_last (test_input)

7 [[[22 13 17 11  0]
  [ 8  2 23  4 24]
  [21  9 14 16  7]
  [ 6 10  3 18  5]
  [ 1 12 20 15 19]]

 [[ 3 15  0  2 22]
  [ 9 18 13 17  5]
  [19  8  7 25 23]
  [20 11 10 24  4]
  [14 21 16 12  6]]

 [[14 21 17 24  4]
  [10 16 15  9 19]
  [18  8 23 26 20]
  [22 11 13  6  5]
  [ 2  0 12  3  7]]]
7 [[[22 13 17 11  0]
  [ 8  2 23  4 24]
  [21  9 14 16 -1]
  [ 6 10  3 18  5]
  [ 1 12 20 15 19]]

 [[ 3 15  0  2 22]
  [ 9 18 13 17  5]
  [19  8 -1 25 23]
  [20 11 10 24  4]
  [14 21 16 12  6]]

 [[14 21 17 24  4]
  [10 16 15  9 19]
  [18  8 23 26 20]
  [22 11 13  6  5]
  [ 2  0 12  3 -1]]]
4 [[[22 13 17 11  0]
  [ 8  2 23  4 24]
  [21  9 14 16 -1]
  [ 6 10  3 18  5]
  [ 1 12 20 15 19]]

 [[ 3 15  0  2 22]
  [ 9 18 13 17  5]
  [19  8 -1 25 23]
  [20 11 10 24  4]
  [14 21 16 12  6]]

 [[14 21 17 24  4]
  [10 16 15  9 19]
  [18  8 23 26 20]
  [22 11 13  6  5]
  [ 2  0 12  3 -1]]]
4 [[[22 13 17 11  0]
  [ 8  2 23 -1 24]
  [21  9 14 16 -1]
  [ 6 10  3 18  5]
  [ 1 12 20 15 19]]

 [[ 3 15  0  2 22]
  [

1924

In [86]:
%run ./util.ipynb
play_bingo(read_file('day4'))

4 [[[30 46 94 20  2]
  [53 67 69 75 65]
  [27 24 85 28 60]
  [57 58 42 36 78]
  [35 98 87 91 93]]

 [[72 71 91 73 19]
  [ 2 13 14  8 74]
  [42 34 31 56  9]
  [82 59 44 67 79]
  [49  6 98 10 30]]

 [[95 24 25 11 34]
  [57 65 41 92  8]
  [91 26  1 62 38]
  [47 93  4 37  0]
  [15 44 33 20 97]]

 ...

 [[20 80 50 27 90]
  [21 35  9 40 81]
  [89 16 26 74 84]
  [29 97 88 19 32]
  [85 63 10 46 52]]

 [[16 66  0 53 40]
  [94 42 80 86 25]
  [11 15 68 35  5]
  [60 89 41 92 79]
  [51 77 88 36 67]]

 [[51 65 33 97 81]
  [78 96 86 64 22]
  [10 28 93  2 14]
  [71 29 92  6 62]
  [98 38 35  0 70]]]
4 [[[30 46 94 20  2]
  [53 67 69 75 65]
  [27 24 85 28 60]
  [57 58 42 36 78]
  [35 98 87 91 93]]

 [[72 71 91 73 19]
  [ 2 13 14  8 74]
  [42 34 31 56  9]
  [82 59 44 67 79]
  [49  6 98 10 30]]

 [[95 24 25 11 34]
  [57 65 41 92  8]
  [91 26  1 62 38]
  [47 93 -1 37  0]
  [15 44 33 20 97]]

 ...

 [[20 80 50 27 90]
  [21 35  9 40 81]
  [89 16 26 74 84]
  [29 97 88 19 32]
  [85 63 10 46 52]]

 [[16 66  0 53

38913

In [105]:
%run ./util.ipynb
play_bingo_last(read_file('day4'))

4 [[[30 46 94 20  2]
  [53 67 69 75 65]
  [27 24 85 28 60]
  [57 58 42 36 78]
  [35 98 87 91 93]]

 [[72 71 91 73 19]
  [ 2 13 14  8 74]
  [42 34 31 56  9]
  [82 59 44 67 79]
  [49  6 98 10 30]]

 [[95 24 25 11 34]
  [57 65 41 92  8]
  [91 26  1 62 38]
  [47 93  4 37  0]
  [15 44 33 20 97]]

 ...

 [[20 80 50 27 90]
  [21 35  9 40 81]
  [89 16 26 74 84]
  [29 97 88 19 32]
  [85 63 10 46 52]]

 [[16 66  0 53 40]
  [94 42 80 86 25]
  [11 15 68 35  5]
  [60 89 41 92 79]
  [51 77 88 36 67]]

 [[51 65 33 97 81]
  [78 96 86 64 22]
  [10 28 93  2 14]
  [71 29 92  6 62]
  [98 38 35  0 70]]]
4 [[[30 46 94 20  2]
  [53 67 69 75 65]
  [27 24 85 28 60]
  [57 58 42 36 78]
  [35 98 87 91 93]]

 [[72 71 91 73 19]
  [ 2 13 14  8 74]
  [42 34 31 56  9]
  [82 59 44 67 79]
  [49  6 98 10 30]]

 [[95 24 25 11 34]
  [57 65 41 92  8]
  [91 26  1 62 38]
  [47 93 -1 37  0]
  [15 44 33 20 97]]

 ...

 [[20 80 50 27 90]
  [21 35  9 40 81]
  [89 16 26 74 84]
  [29 97 88 19 32]
  [85 63 10 46 52]]

 [[16 66  0 53

16836